### ISSUE TITLE
The Chinese input of QT5 in linux is incorrect

### ISSUE THREAD

**Issue by jwj76** [davidbannon/libqt5pas#57] opened 2024-01-08 03:40 UTC
1.'不' cannot be entered.TComboBox TEdit Existing problem
2. '有'After typing, it will jump to the next control, just like pressing the TAB key.All input controls are involved.
3. You can only enter a maximum of two phrases, and if there are more than three, only the first two will be displayed.All input controls are involved.

I have a feeling it's Libqt5pas. Because 1. compiling with gtk2 is fine, Lazarus is normal, 2. Qt5 software developed in other languages does not have problems, which means that qt5 itself does not have this problem. So the most likely problem is with Libqt5pas.

**Comment by davidbannon** [comment] 2024-01-08 21:48
So, the problem is specifially those two "characters" - all the other one (tested) work OK ?

Can you please test with gtk2 ?  That would tell us, clearly, if its a Qt5 issue.

Either way, you or I will need to log this as a bug with Lazarus it self over in Gitlab. All I do here is build and package the libraries. But lets get the story clear first.

Davo

**Comment by davidbannon** [comment] 2024-01-17 07:23
Any further thoughts here [jwj76](https://github.com/jwj76) ?

Davo

**Comment by davidbannon** [comment] 2024-03-21 12:06
No answer from [jwj76](https://github.com/jwj76), 
I'll close this issue.
David

**Closed by davidbannon** 2024-03-21 12:06 UTC
